title: "AGI時代の好き本位体制 for all their lifetime, be an honest person."
summary: "本書は筆者の好きを詰め込んだ縦書き印刷、装丁、表紙と書籍版がメインになっているので、是非書籍版も一度手に取っていただけたら、幸いです。さて、こちらのZennBook版は序章・第1章・あとがき・参考資料1(デンマークのデジタル教育改革の検証)・書誌は無料でご覧いただけます。"
topics: ["AI", "教育", "子育て", "AGI"]
published: true
price: 800
chapters:
  - 00-jo
  - 01-suki-no-koujigenba
  - 02-nande-sukinano-ga-kowasu-mono
  - 03-setsunai-wo-te-ni-ireru
  - 04-hanauta-to-haiku
  - 05-yohaku-to-taikutsu
  - 06-najimi
  - 07-gikou-wa-iru
  - 08-minna-ga-suki-no-atesaki
  - 09-gyousha-ni-naranai-oya
  - 10-kyouiku-gakkou-gakuryoku
  - 11-c-kabe-to-newmath
  - 12-sotsu-no-nai-kotae-demo-ikisaki-wa-kimaranai
  - 13-umai-kotae-ga-attemo-jibun-de-yaru
  - 14-hata-ga-hitorideni-nuno-wo-orunara
  - 16-saishuushou-erabu-kaisuu-wa-herasanai
  - 28-kenkyuu-to-honsho-no-seiri
  - 30-misaki
  - 27-denmark-no-shippai
  - 29-shoshi-dai1bu
  - 30-shoshi-dai2bu
